name: Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  docker-build:
    name: Docker build
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build application image
        run: docker build .
